name: Android Tests CI

on:
  push:
    branches: [ "dev", "main" ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/update-gradle-wrapper.yml'
  pull_request:
    branches: [ "dev" ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/update-gradle-wrapper.yml'
  workflow_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew test
